# Generated by Django 5.1.6 on 2025-02-25 13:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('file_url', models.URLField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parser_group', models.CharField(choices=[('1', 'soccerway_1'), ('2', 'soccerway_2'), ('M', 'marafon')], max_length=1)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
