# Generated by Django 5.1.6 on 2025-02-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_s3_key_alter_file_parser_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='s3_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
